server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata

seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    #type: file
    type: nacos
    nacos:
      application: seata-server
      server-addr: 172.18.0.2:8848 #nacos容器的ip，非系统
      group: SEATA_GROUP
      namespace: 4b70485d-72dd-44df-a76a-7a3f578a3001
      dataId: 'seataServer.properties'
      cluster: default
      username: nacos
      password: ciwei@nacos
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    # type: file
    type: nacos
    nacos:
      application: seata-server
      server-addr: 172.18.0.2:8848
      group: SEATA_GROUP
      namespace: 4b70485d-72dd-44df-a76a-7a3f578a3001
      cluster: default
      username: nacos
      password: ciwei@nacos
  store:
    # support: file 、 db 、 redis 、 raft
    #mode: file
    mode: db
    db:
      datasource: druid
      db-type: mysql
      #mysql5
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #mysql5
      #url: jdbc:mysql://127.0.0.1:3306/mall4cloud_seata?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      #mysql8
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.1.188:3306/mall4cloud_seata?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      user: root
      password: ciwei@hg2024%

  #  server:
  #    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/api/v1/auth/login